os: linux
language: cpp
compiler: gcc
dist: xenial

before_install:
 - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo add-apt-repository -y ppa:beineri/opt-qt-5.12.3-xenial; fi
 - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update -qq; fi
 - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install libmbim-glib4 libmbim-proxy libqmi-glib5 libqmi-proxy qutebrowser-qtwebengine qml-module-qtwebengine python3-pyqt5.qtwebengine; fi

script:
    - qmake
    - make
